# EXPERIMENT 2 | Dwayne Pendilla | 2ECE-C

***NORMALIZATION PROBLEM***

In [3]:
import numpy as np

In [17]:
# Generate the 5x5 array with random numbers
x = np.random.random((5,5))
# Get the Mean and Standard Dev of the Array
y = x.mean()
z = x.std()

# Normalized x
normx = (x-y)/z
print(normx)

[[-1.32065958  1.17068468 -1.40097199  1.92335374  1.22825283]
 [-0.20323802 -0.54218002 -0.40045438 -0.67061986  1.05677878]
 [-0.51937567 -0.06857632  0.85399815  0.26301573  0.71434929]
 [-1.02728126 -0.91021011  1.64706253  1.21208174 -0.09237526]
 [-0.21795145  0.8451867  -1.00946065 -1.33714598 -1.19426362]]


In [15]:
# Generate the 5x5 array with random numbers
prog = np.random.random((5, 5))
# Get the Mean and Standard Dev of the Array
y = prog.mean()
z = prog.std()

# Normalized prog
normprog = (prog-y)/z
print(normprog)

[[-1.08562831 -0.4285293   0.86498495  1.19126272 -1.13288855]
 [-0.45165654 -0.44870269 -0.22720696  0.78724219 -0.73562081]
 [ 1.8775793  -0.3357337  -1.34529986 -1.58763416  0.06295943]
 [-0.47268579  2.1765985   0.62960567  0.49989006 -0.89206262]
 [-0.79368255 -0.49729499  1.31465268  1.2422044  -0.21235305]]


***DIVISIBLE BY 3 PROBLEM***

In [228]:
# Generate the 10x10 array with the square of the first 100 pos integers
d = np.arange(1,101).reshape(10,10)**2
# Find all elements divisible by 3
by3 = d[d % 3 == 0].reshape(3,11)

# Print the 10x10 array and the elements divisble by 3
print("Array of squares: \n", d)
print("\nElements divisible by 3: \n", by3)

Array of squares: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]


## Thank you!