# EXPERIMENT 2 | Dwayne Pendilla | 2ECE-C

***NORMALIZATION PROBLEM***

In [9]:
import numpy as np

In [15]:
# Generate the 5x5 array with random numbers
x = np.random.random((5,5))
# Get the Mean and Standard Dev of the Array
y = x.mean()
z = x.std()

# Normalized x
normx = (x-y)/z
print(normx)

[[-0.35285264  0.48954446 -0.39140255 -0.70094645 -0.82313116]
 [ 1.02429158  0.89653773  0.99335669 -0.08947939  1.54259174]
 [-1.39218093  0.24307406 -0.67864008  1.47997975  2.07400867]
 [-1.08806247  1.35633931 -1.12786656  0.14899238  0.87324761]
 [-0.74561542 -0.93598438 -0.95204579 -1.01756708 -0.82618909]]


In [17]:
# Generate the 5x5 array with random numbers
prog = np.random.random((5, 5))
# Get the Mean and Standard Dev of the Array
y = prog.mean()
z = prog.std()

# Normalized prog
normprog = (prog-y)/z
print(normprog)

[[ 0.1241402   0.82599337  0.73346779  1.52208638 -0.33319395]
 [-0.20773483 -1.61947072 -0.1235819   1.4917289  -1.34784384]
 [-1.64807559  1.40614594 -0.19602226 -0.19263991  1.26896819]
 [-0.05636224 -0.41901249 -0.7089994  -0.79995213  0.28986408]
 [ 1.13951457  1.64750763 -0.64392189 -1.28207015 -0.87053576]]
